spring.application.name=desafio-votacao
server.servlet.context-path=/api/v1
# Conexão com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/votacao
spring.datasource.username=votacao
spring.datasource.password=votacao
# Fuso das datas no JSON (ex.: UTC, America/Sao_Paulo)
spring.jackson.time-zone=UTC
# Cliente fake de validacao de CPF (bonus 1)
cpf.cliente.aleatorio=true
cpf.cliente.resultado-fixo=ABLE_TO_VOTE
